name: Update nixpkgs

on:
  schedule:
    - cron:  '0 1 * * 0'
  workflow_dispatch:

jobs:
  nixpkgs-update:
    name: Update nixpkgs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          ref: main
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Run flake update
        run: >
          nix flake update nixpkgs-26-5 nixpkgs-unstable

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          git add flake.lock
          git diff --cached --quiet || git commit -m "flake: flake update nixpkgs-26-5 nixpkgs-unstable"
          git push origin main

